const ON_PILE = 0;
const ON_TABLE = 1;
const ON_HAND = 2;
const ON_GRAVEYARD = 3;

const DECK_SIZE = 82;
const DEFAULT_CARD_WIDTH = 262;
const DEFAULT_CARD_HEIGHT = 375;

const ACTION_PLAYER_JOIN = 0;
const ACTION_DM_JOIN = 1;
const ACTION_PLAYER_SETUP = 2;
const ACTION_OK = 3;
const ACTION_ADD_DM = 4;
const ACTION_ADD_PLAYER = 5;
const ACTION_DRAW_TO_TABLE = 6;
const ACTION_SEND_TABLE_TO_GRAVEYARD = 7;
const ACTION_GIVE_INITIAL_HAND = 8;
const ACTION_DRAW_TO_POOL = 9;
const ACTION_GIVE_TURN = 10;
const ACTION_PUT_BACK_IN_POOL = 11;
const ACTION_PLAY_FROM_POOL = 12;
const ACTION_SHUFFLE_GRAVEYARD_INTO_PILE = 13;
